/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x7ef69b = _0x4a51;
(function (_0x314a9d, _0x2a3fa7) {
    const _0xf6ece6 = _0x4a51, _0x216bc5 = _0x314a9d();
    while (!![]) {
        try {
            const _0x41c916 = -parseInt(_0xf6ece6(0x177)) / 0x1 + -parseInt(_0xf6ece6(0x18c)) / 0x2 * (parseInt(_0xf6ece6(0x18e)) / 0x3) + -parseInt(_0xf6ece6(0x17c)) / 0x4 * (parseInt(_0xf6ece6(0x183)) / 0x5) + parseInt(_0xf6ece6(0x17e)) / 0x6 * (parseInt(_0xf6ece6(0x17d)) / 0x7) + -parseInt(_0xf6ece6(0x181)) / 0x8 + parseInt(_0xf6ece6(0x15f)) / 0x9 * (parseInt(_0xf6ece6(0x162)) / 0xa) + parseInt(_0xf6ece6(0x16b)) / 0xb;
            if (_0x41c916 === _0x2a3fa7)
                break;
            else
                _0x216bc5['push'](_0x216bc5['shift']());
        } catch (_0x1d2be5) {
            _0x216bc5['push'](_0x216bc5['shift']());
        }
    }
}(_0x337e, 0x6d3a0));
function _0x337e() {
    const _0x4fa586 = [
        'CiTqU',
        '672264NWYRJP',
        'readFile',
        '5obrmwf',
        '/s-',
        'moreStatus',
        '\x20not\x20found\x20for\x20group\x0a',
        'base64',
        'exports',
        'XGnMw',
        'EgaAG',
        'Azjtu',
        '1310MMEnAT',
        'del',
        '3000VnDCjn',
        'wIQOD',
        'exists',
        'BgZXv',
        'serialize',
        'XsyzY',
        'put',
        '90tYOqwi',
        'toString',
        'Jilzi',
        '7660tBfcDn',
        'existsSync',
        'cCmLI',
        'object',
        'WbzhO',
        'key',
        'MsReo',
        '../../store',
        'szkNY',
        '15867599mSXfKE',
        'FLjSk',
        'string',
        'join',
        'from',
        'LDznl',
        'deserialize',
        'mkdirSync',
        'sid',
        'writeFile',
        'split',
        'local',
        '477228CdWcpM',
        'PfhAU',
        'gid',
        'ehJRL',
        'HZtJL',
        '423796uSCfDt',
        '7XLKFlW',
        '1916598cSEfuO',
        'AdXZy'
    ];
    _0x337e = function () {
        return _0x4fa586;
    };
    return _0x337e();
}
const fs = require('fs'), path = require('path'), id = require('../util/id'), serialization = require('../util/serialization'), store = {}, baseFolder = path[_0x7ef69b(0x16e)](__dirname, _0x7ef69b(0x169));
!fs[_0x7ef69b(0x163)](baseFolder + '/s-' + global[_0x7ef69b(0x185)][_0x7ef69b(0x173)]) && fs[_0x7ef69b(0x172)](baseFolder + _0x7ef69b(0x184) + global[_0x7ef69b(0x185)][_0x7ef69b(0x173)]);
function normalize(_0x4ba11d) {
    const _0x5cb419 = _0x7ef69b, _0x200e19 = {
            'wIQOD': function (_0x36a66e, _0x21b69b) {
                return _0x36a66e === _0x21b69b;
            },
            'HZtJL': _0x5cb419(0x16d),
            'XsyzY': 'local',
            'MsReo': function (_0x3f5456, _0x128f37) {
                return _0x3f5456 === _0x128f37;
            },
            'CiTqU': _0x5cb419(0x165)
        };
    let _0x511d2f = {};
    _0x200e19[_0x5cb419(0x18f)](_0x4ba11d, null) && (_0x4ba11d = {});
    if (_0x200e19[_0x5cb419(0x18f)](typeof _0x4ba11d, _0x200e19[_0x5cb419(0x17b)]))
        _0x511d2f[_0x5cb419(0x167)] = _0x4ba11d, _0x511d2f[_0x5cb419(0x179)] = _0x200e19[_0x5cb419(0x193)];
    else
        _0x200e19[_0x5cb419(0x168)](typeof _0x4ba11d, _0x200e19[_0x5cb419(0x180)]) && (_0x511d2f['key'] = _0x4ba11d['key'], _0x511d2f[_0x5cb419(0x179)] = _0x4ba11d[_0x5cb419(0x179)]);
    return _0x511d2f;
}
;
function _0x4a51(_0x248139, _0x34b31e) {
    const _0x337e2d = _0x337e();
    return _0x4a51 = function (_0x4a5158, _0x3d69d1) {
        _0x4a5158 = _0x4a5158 - 0x15f;
        let _0x470b07 = _0x337e2d[_0x4a5158];
        return _0x470b07;
    }, _0x4a51(_0x248139, _0x34b31e);
}
store[_0x7ef69b(0x194)] = function (_0x2f24e7, _0x2e799a, _0x53d781) {
    const _0x3f02af = _0x7ef69b, _0x3b2253 = {
            'EgaAG': function (_0x5659bc, _0x38585a, _0x3f3c51) {
                return _0x5659bc(_0x38585a, _0x3f3c51);
            },
            'Azjtu': function (_0x17e588, _0xb07978) {
                return _0x17e588(_0xb07978);
            },
            'cCmLI': _0x3f02af(0x176)
        };
    _0x53d781 = _0x53d781 || function () {
    }, _0x2e799a = _0x3b2253[_0x3f02af(0x18b)](normalize, _0x2e799a), _0x2e799a[_0x3f02af(0x167)] = _0x2e799a[_0x3f02af(0x167)] || id['getID'](_0x2f24e7), _0x2e799a[_0x3f02af(0x179)] = _0x2e799a[_0x3f02af(0x179)] || _0x3b2253[_0x3f02af(0x164)];
    let _0x4af56d = serialization[_0x3f02af(0x192)](_0x2f24e7), _0x50e57e = Buffer[_0x3f02af(0x16f)](_0x2e799a[_0x3f02af(0x167)])[_0x3f02af(0x160)](_0x3f02af(0x187));
    _0x50e57e = baseFolder + _0x3f02af(0x184) + global[_0x3f02af(0x185)][_0x3f02af(0x173)] + '/' + _0x2e799a[_0x3f02af(0x179)] + '-' + _0x50e57e, fs[_0x3f02af(0x174)](_0x50e57e, _0x4af56d, _0x1a6ecc => {
        const _0x37bb89 = _0x3f02af;
        _0x1a6ecc ? _0x53d781(_0x1a6ecc) : _0x3b2253[_0x37bb89(0x18a)](_0x53d781, null, _0x2f24e7);
    });
}, store['get'] = function (_0x5236f6, _0x3e930c) {
    const _0x1317e9 = _0x7ef69b, _0x366a35 = {
            'XGnMw': function (_0x31fa7e, _0x1288c1) {
                return _0x31fa7e(_0x1288c1);
            },
            'FLjSk': function (_0x149625, _0x10e719) {
                return _0x149625 < _0x10e719;
            },
            'BgZXv': function (_0xde3166, _0x176710) {
                return _0xde3166 - _0x176710;
            },
            'LDznl': 'base64',
            'ehJRL': function (_0x2e60fd, _0x5221f9, _0x48cc7f) {
                return _0x2e60fd(_0x5221f9, _0x48cc7f);
            },
            'szkNY': function (_0x3f1202, _0x5506f8) {
                return _0x3f1202(_0x5506f8);
            }
        };
    _0x3e930c = _0x3e930c || function () {
    }, _0x5236f6 = _0x366a35[_0x1317e9(0x189)](normalize, _0x5236f6), _0x5236f6[_0x1317e9(0x179)] = _0x5236f6[_0x1317e9(0x179)] || _0x1317e9(0x176);
    if (!_0x5236f6[_0x1317e9(0x167)]) {
        fs['readdir'](baseFolder + _0x1317e9(0x184) + global[_0x1317e9(0x185)][_0x1317e9(0x173)], (_0x8b129c, _0x50696c) => {
            const _0x227891 = _0x1317e9;
            if (_0x8b129c)
                _0x366a35[_0x227891(0x189)](_0x3e930c, _0x8b129c);
            else {
                let _0x5bf617 = [];
                for (let _0x506797 = 0x0; _0x366a35[_0x227891(0x16c)](_0x506797, _0x50696c['length']); _0x506797++) {
                    let _0x355776 = _0x50696c[_0x506797][_0x227891(0x175)]('-'), _0x2b7721 = _0x355776[0x0];
                    if (_0x2b7721 !== _0x5236f6[_0x227891(0x179)])
                        continue;
                    _0x355776 = _0x355776[_0x366a35[_0x227891(0x191)](_0x355776['length'], 0x1)], _0x5bf617['push'](Buffer[_0x227891(0x16f)](_0x355776, _0x366a35['LDznl'])['toString']());
                }
                _0x366a35[_0x227891(0x17a)](_0x3e930c, null, _0x5bf617);
            }
        });
        return;
    }
    let _0x131197 = Buffer[_0x1317e9(0x16f)](_0x5236f6[_0x1317e9(0x167)])['toString'](_0x366a35[_0x1317e9(0x170)]);
    _0x131197 = baseFolder + '/s-' + global[_0x1317e9(0x185)]['sid'] + '/' + _0x5236f6[_0x1317e9(0x179)] + '-' + _0x131197, fs[_0x1317e9(0x190)](_0x131197, _0x11fb60 => {
        const _0x5c05a5 = _0x1317e9;
        if (!_0x11fb60) {
            _0x366a35[_0x5c05a5(0x16a)](_0x3e930c, new Error('File\x20' + _0x131197 + '\x20not\x20found\x20for\x20group\x0a' + _0x5236f6[_0x5c05a5(0x179)]));
            return;
        }
        fs[_0x5c05a5(0x182)](_0x131197, (_0x4931a2, _0x1466d9) => {
            const _0x1a930f = _0x5c05a5;
            _0x1466d9 = _0x1466d9[_0x1a930f(0x160)]();
            if (!_0x3e930c)
                return;
            _0x4931a2 ? _0x366a35[_0x1a930f(0x189)](_0x3e930c, _0x4931a2) : _0x366a35[_0x1a930f(0x17a)](_0x3e930c, null, serialization[_0x1a930f(0x171)](_0x1466d9));
        });
    });
}, store[_0x7ef69b(0x18d)] = function (_0xbd11bc, _0x5e8376) {
    const _0x40dab6 = _0x7ef69b, _0x5a45f9 = {
            'Jilzi': function (_0x30b4f2, _0x459356) {
                return _0x30b4f2(_0x459356);
            },
            'PfhAU': function (_0x392dff, _0x4b6214) {
                return _0x392dff(_0x4b6214);
            }
        };
    _0x5e8376 = _0x5e8376 || function () {
    }, _0xbd11bc = _0x5a45f9[_0x40dab6(0x178)](normalize, _0xbd11bc);
    let _0x167dd3 = Buffer[_0x40dab6(0x16f)](_0xbd11bc['key'])[_0x40dab6(0x160)](_0x40dab6(0x187));
    _0x167dd3 = baseFolder + _0x40dab6(0x184) + global[_0x40dab6(0x185)]['sid'] + '/' + _0xbd11bc[_0x40dab6(0x179)] + '-' + _0x167dd3, fs[_0x40dab6(0x190)](_0x167dd3, _0x223bdc => {
        const _0x1a918e = _0x40dab6, _0x4a1cb1 = {
                'AdXZy': function (_0x70f519, _0x24116f) {
                    const _0xb45c79 = _0x4a51;
                    return _0x5a45f9[_0xb45c79(0x161)](_0x70f519, _0x24116f);
                },
                'WbzhO': function (_0x404fde, _0x1a3bde, _0x139f80) {
                    return _0x404fde(_0x1a3bde, _0x139f80);
                }
            };
        if (!_0x223bdc) {
            _0x5a45f9[_0x1a918e(0x161)](_0x5e8376, new Error('File\x20' + _0x167dd3 + _0x1a918e(0x186) + _0xbd11bc[_0x1a918e(0x179)]));
            return;
        }
        store['get'](_0xbd11bc, (_0x39b70a, _0x1c28c6) => {
            fs['rm'](_0x167dd3, function (_0x3cdc33) {
                const _0x1cf017 = _0x4a51;
                _0x3cdc33 ? _0x4a1cb1[_0x1cf017(0x17f)](_0x5e8376, _0x3cdc33) : _0x4a1cb1[_0x1cf017(0x166)](_0x5e8376, null, _0x1c28c6);
            });
        });
    });
}, module[_0x7ef69b(0x188)] = store;/* eslint-enable */
