/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
function _0x8695(_0x4a3a86, _0x242ca9) {
    const _0xd144c0 = _0xd144();
    return _0x8695 = function (_0x86952b, _0x3d1ffb) {
        _0x86952b = _0x86952b - 0xf7;
        let _0x3613c9 = _0xd144c0[_0x86952b];
        return _0x3613c9;
    }, _0x8695(_0x4a3a86, _0x242ca9);
}
const _0x3cc09e = _0x8695;
(function (_0x355381, _0x22da88) {
    const _0x318cb4 = _0x8695, _0x2b87b1 = _0x355381();
    while (!![]) {
        try {
            const _0x244712 = -parseInt(_0x318cb4(0x135)) / 0x1 + -parseInt(_0x318cb4(0x124)) / 0x2 * (parseInt(_0x318cb4(0x11c)) / 0x3) + -parseInt(_0x318cb4(0x111)) / 0x4 * (-parseInt(_0x318cb4(0x12a)) / 0x5) + parseInt(_0x318cb4(0x101)) / 0x6 * (parseInt(_0x318cb4(0x12d)) / 0x7) + parseInt(_0x318cb4(0x10b)) / 0x8 * (-parseInt(_0x318cb4(0xff)) / 0x9) + parseInt(_0x318cb4(0x113)) / 0xa + parseInt(_0x318cb4(0x104)) / 0xb;
            if (_0x244712 === _0x22da88)
                break;
            else
                _0x2b87b1['push'](_0x2b87b1['shift']());
        } catch (_0x4e4b1a) {
            _0x2b87b1['push'](_0x2b87b1['shift']());
        }
    }
}(_0xd144, 0xbb164));
function _0xd144() {
    const _0x897bee = [
        'getNID',
        '[DISTRIBUTED\x20STORE]\x20PUT\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20State:\x20',
        'length',
        'concat',
        '51tcNvFL',
        'substring',
        'put',
        'lQRwa',
        '[DISTRIBUTED\x20STORE]\x20GET\x20NODE\x0a\x20\x20\x20\x20\x20\x20\x20\x20Configuration:\x20',
        'gPJEY',
        'iNTQK',
        'OUkbU',
        '122700NKFwlD',
        'tqGgS',
        'local',
        'gid',
        'send',
        'ORvkV',
        '76700vOZidV',
        'pyRju',
        'IgorB',
        '577416NiQhzw',
        'map',
        'comm',
        'zkMon',
        'distribution',
        '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Target\x20Node:\x20',
        'log',
        'bPHOa',
        '106150eSdgoY',
        '\x0a\x20\x20\x20\x20\x20\x20\x20\x20NODE:\x20',
        'groups',
        'UjERh',
        '\x0a\x20\x20\x20\x20\x20\x20\x20\x20',
        'jdoVR',
        'BQmIv',
        'nid',
        'values',
        'wDsEW',
        'xsbZF',
        '4725225loxNHT',
        'get',
        '96LjjLcX',
        'TwAep',
        'Ktuwh',
        '1759571dcVtdl',
        'lZQVF',
        '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20',
        'naiveHash',
        'store',
        'reduce',
        'stringify',
        '8XBHvDc',
        'hash',
        '[DISTRIBUTED\x20STORE]\x20GET\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Configuration:\x20',
        'rQaVW',
        'VKfhi',
        'del',
        '140jCuotn',
        'nodeConfig',
        '4237640ehSXpb',
        'getID',
        'wuWqb',
        'NbASA',
        'status'
    ];
    _0xd144 = function () {
        return _0x897bee;
    };
    return _0xd144();
}
const util = require('../util/util'), distribution = global[_0x3cc09e(0x131)];
function getNode(_0x2de9fb, _0x27fc9f, _0x2ed2c4) {
    const _0x3fd3cf = _0x3cc09e, _0x194e2 = {
            'OUkbU': function (_0x28366e, _0x1e4e62) {
                return _0x28366e(_0x1e4e62);
            }
        };
    distribution[_0x2de9fb[_0x3fd3cf(0x127)]][_0x3fd3cf(0x117)][_0x3fd3cf(0x100)](_0x3fd3cf(0xfb), (_0x5ba96d, _0x18c7b3) => {
        const _0x3dd96b = _0x3fd3cf;
        let _0x413695 = Object[_0x3dd96b(0xfc)](_0x18c7b3), _0x31cf05 = util['id']['getID'](_0x27fc9f), _0x17c3ec = _0x2de9fb[_0x3dd96b(0x10c)](_0x31cf05, _0x413695), _0x3d1526 = _0x17c3ec[_0x3dd96b(0x11d)](0x0, 0x5);
        console[_0x3dd96b(0x133)](_0x3dd96b(0x120) + JSON['stringify'](_0x27fc9f) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20GID:\x20' + JSON[_0x3dd96b(0x10a)](_0x2de9fb['gid']) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20NID\x20List:\x20' + JSON['stringify'](_0x413695) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20NID:\x20' + JSON[_0x3dd96b(0x10a)](_0x17c3ec) + _0x3dd96b(0x136) + JSON[_0x3dd96b(0x10a)](global[_0x3dd96b(0x112)]) + _0x3dd96b(0xf8)), distribution[_0x3dd96b(0x126)][_0x3dd96b(0x137)][_0x3dd96b(0x100)](_0x2de9fb[_0x3dd96b(0x127)], (_0x44f79e, _0x507b31) => {
            const _0x334588 = _0x3dd96b;
            let _0x242341 = _0x507b31[_0x3d1526];
            _0x194e2[_0x334588(0x123)](_0x2ed2c4, _0x242341);
        });
    });
}
const store = function (_0x66d0fe) {
    const _0x357386 = _0x3cc09e, _0x3c5a82 = {
            'ogNLu': function (_0x7484e, _0x2fc3b4, _0x14095c) {
                return _0x7484e(_0x2fc3b4, _0x14095c);
            },
            'UjERh': _0x357386(0x108),
            'bPHOa': function (_0x4427f6, _0x3c4ab6, _0x191164, _0x59e0f7) {
                return _0x4427f6(_0x3c4ab6, _0x191164, _0x59e0f7);
            },
            'iNTQK': _0x357386(0x110),
            'TwAep': function (_0x2de75b, _0x5b5e32) {
                return _0x2de75b === _0x5b5e32;
            },
            'IgorB': function (_0x4a7599) {
                return _0x4a7599();
            },
            'pyRju': 'nid',
            'gPJEY': 'all'
        };
    let _0x57bca1 = {};
    return _0x57bca1['gid'] = _0x66d0fe[_0x357386(0x127)] || _0x3c5a82[_0x357386(0x121)], _0x57bca1[_0x357386(0x10c)] = _0x66d0fe[_0x357386(0x10c)] || util['id'][_0x357386(0x107)], {
        'get': (_0x4ff058, _0x21d452) => {
            const _0x43e353 = _0x357386, _0xa4c4ec = {
                    'ORvkV': function (_0x577bd6, _0x156baf, _0x5cbc6a) {
                        return _0x3c5a82['ogNLu'](_0x577bd6, _0x156baf, _0x5cbc6a);
                    },
                    'BQmIv': _0x3c5a82[_0x43e353(0xf7)]
                };
            if (!_0x4ff058) {
                let _0x14c40c = [{
                        'key': null,
                        'gid': _0x57bca1[_0x43e353(0x127)]
                    }];
                distribution[_0x57bca1['gid']][_0x43e353(0x12f)][_0x43e353(0x128)](_0x14c40c, {
                    'service': 'store',
                    'method': _0x43e353(0x100)
                }, (_0x376c1b, _0x464843) => {
                    const _0x12ce88 = _0x43e353;
                    let _0x5da1ee = Object['values'](_0x464843)[_0x12ce88(0x109)]((_0x1129b2, _0x5e20b6) => _0x1129b2[_0x12ce88(0x11b)](_0x5e20b6), []);
                    _0xa4c4ec[_0x12ce88(0x129)](_0x21d452, _0x376c1b, _0x5da1ee);
                });
                return;
            }
            _0x3c5a82[_0x43e353(0x134)](getNode, _0x57bca1, _0x4ff058, _0x4dbb99 => {
                const _0x38c3f4 = _0x43e353;
                let _0xd38d5d = [{
                            'key': _0x4ff058,
                            'gid': _0x57bca1[_0x38c3f4(0x127)]
                        }], _0x4b71a9 = {
                        'service': _0xa4c4ec[_0x38c3f4(0xfa)],
                        'method': _0x38c3f4(0x100),
                        'node': _0x4dbb99
                    };
                console[_0x38c3f4(0x133)](_0x38c3f4(0x10d) + JSON[_0x38c3f4(0x10a)](_0x4ff058) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Node:\x20' + JSON[_0x38c3f4(0x10a)](global[_0x38c3f4(0x112)]) + _0x38c3f4(0x132) + JSON[_0x38c3f4(0x10a)](_0x4dbb99) + _0x38c3f4(0x106)), distribution[_0x38c3f4(0x126)][_0x38c3f4(0x12f)][_0x38c3f4(0x128)](_0xd38d5d, _0x4b71a9, _0x21d452);
            });
        },
        'put': (_0x4c8b32, _0x30301b, _0x5522fa) => {
            const _0x10ed72 = _0x357386, _0x38cb3e = {
                    'wDsEW': _0x3c5a82[_0x10ed72(0xf7)],
                    'lQRwa': 'put'
                };
            _0x30301b = _0x30301b || util['id'][_0x10ed72(0x114)](_0x4c8b32), _0x3c5a82['bPHOa'](getNode, _0x57bca1, _0x30301b, _0x3e4173 => {
                const _0x211db0 = _0x10ed72;
                let _0x175e0b = [
                        _0x4c8b32,
                        {
                            'key': _0x30301b,
                            'gid': _0x57bca1[_0x211db0(0x127)]
                        }
                    ], _0x1a587e = {
                        'service': _0x38cb3e[_0x211db0(0xfd)],
                        'method': _0x38cb3e[_0x211db0(0x11f)],
                        'node': _0x3e4173
                    };
                console[_0x211db0(0x133)](_0x211db0(0x119) + JSON[_0x211db0(0x10a)](_0x4c8b32) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Configuration:\x20' + JSON[_0x211db0(0x10a)](_0x30301b) + '\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Node:\x20' + JSON[_0x211db0(0x10a)](global[_0x211db0(0x112)]) + _0x211db0(0x132) + JSON[_0x211db0(0x10a)](_0x3e4173) + _0x211db0(0x106)), distribution[_0x211db0(0x126)][_0x211db0(0x12f)][_0x211db0(0x128)](_0x175e0b, _0x1a587e, _0x5522fa);
            });
        },
        'del': (_0x12e8bd, _0x591672) => {
            const _0x5da06e = _0x357386, _0x4d6c00 = {
                    'tqGgS': _0x3c5a82[_0x5da06e(0xf7)],
                    'rQaVW': _0x3c5a82[_0x5da06e(0x122)]
                };
            _0x3c5a82[_0x5da06e(0x134)](getNode, _0x57bca1, _0x12e8bd, _0x13ae96 => {
                const _0x4432bf = _0x5da06e;
                let _0x4ab7a1 = [{
                            'key': _0x12e8bd,
                            'gid': _0x57bca1[_0x4432bf(0x127)]
                        }], _0x43d7b0 = {
                        'service': _0x4d6c00[_0x4432bf(0x125)],
                        'method': _0x4d6c00[_0x4432bf(0x10e)],
                        'node': _0x13ae96
                    };
                distribution[_0x4432bf(0x126)][_0x4432bf(0x12f)][_0x4432bf(0x128)](_0x4ab7a1, _0x43d7b0, _0x591672);
            });
        },
        'reconf': (_0x376e65, _0x4f60c0) => {
            const _0x29ca80 = _0x357386, _0x54ba35 = {
                    'Ktuwh': function (_0x1d283b, _0x3b5fbe) {
                        const _0x138b10 = _0x8695;
                        return _0x3c5a82[_0x138b10(0x102)](_0x1d283b, _0x3b5fbe);
                    },
                    'NbASA': function (_0xe55ba9) {
                        return _0xe55ba9();
                    },
                    'VKfhi': _0x3c5a82[_0x29ca80(0x122)],
                    'lZQVF': function (_0x2e4f4a) {
                        const _0x16a138 = _0x29ca80;
                        return _0x3c5a82[_0x16a138(0x12c)](_0x2e4f4a);
                    },
                    'zkMon': _0x3c5a82[_0x29ca80(0x12b)]
                };
            distribution[_0x57bca1[_0x29ca80(0x127)]][_0x29ca80(0x108)]['get'](null, (_0xf52a96, _0x1bd986) => {
                const _0x4537c2 = _0x29ca80, _0x3f0e77 = {
                        'xsbZF': function (_0x38895a) {
                            const _0x5dfee5 = _0x8695;
                            return _0x54ba35[_0x5dfee5(0x105)](_0x38895a);
                        }
                    };
                distribution[_0x57bca1[_0x4537c2(0x127)]][_0x4537c2(0x117)][_0x4537c2(0x100)](_0x54ba35[_0x4537c2(0x130)], (_0x2a6607, _0x53769a) => {
                    const _0xf7bfeb = _0x4537c2, _0x1d6eae = {
                            'jdoVR': function (_0x2427f3) {
                                return _0x2427f3();
                            }
                        };
                    let _0x39bdaa = Object['values'](_0x53769a), _0x46561a = Object[_0xf7bfeb(0xfc)](_0x376e65)[_0xf7bfeb(0x12e)](_0x3e7ebb => util['id'][_0xf7bfeb(0x118)](_0x3e7ebb)), _0x14e1b4 = 0x0;
                    const _0x490faf = () => {
                        const _0x3beb40 = _0xf7bfeb;
                        _0x14e1b4 === _0x1bd986[_0x3beb40(0x11a)] && _0x1d6eae[_0x3beb40(0xf9)](_0x4f60c0);
                    };
                    if (_0x54ba35[_0xf7bfeb(0x103)](_0x1bd986[_0xf7bfeb(0x11a)], 0x0)) {
                        _0x54ba35[_0xf7bfeb(0x116)](_0x4f60c0);
                        return;
                    }
                    for (let _0x5d317c of _0x1bd986) {
                        let _0xf56bc4 = util['id'][_0xf7bfeb(0x114)](_0x5d317c), _0x53de20 = _0x57bca1[_0xf7bfeb(0x10c)](_0xf56bc4, _0x46561a), _0x550d11 = _0x57bca1[_0xf7bfeb(0x10c)](_0xf56bc4, _0x39bdaa);
                        if (_0x53de20 === _0x550d11) {
                            _0x14e1b4++, _0x490faf();
                            continue;
                        }
                        let _0x3770a5 = _0x376e65[_0x53de20['substring'](0x0, 0x5)], _0x3ac522 = [{
                                    'key': _0x5d317c,
                                    'gid': _0x57bca1[_0xf7bfeb(0x127)]
                                }], _0x5b52eb = {
                                'service': 'store',
                                'method': _0x54ba35[_0xf7bfeb(0x10f)],
                                'node': _0x3770a5
                            };
                        distribution['local'][_0xf7bfeb(0x12f)][_0xf7bfeb(0x128)](_0x3ac522, _0x5b52eb, (_0x5bcebd, _0x3d2298) => {
                            const _0x581a1b = _0xf7bfeb, _0x3d1f00 = {
                                    'wuWqb': function (_0x141033) {
                                        const _0x40e5d4 = _0x8695;
                                        return _0x3f0e77[_0x40e5d4(0xfe)](_0x141033);
                                    }
                                };
                            distribution[_0x57bca1[_0x581a1b(0x127)]][_0x581a1b(0x108)][_0x581a1b(0x11e)](_0x3d2298, _0x5d317c, (_0x2432dc, _0x50e955) => {
                                const _0x359778 = _0x581a1b;
                                _0x14e1b4++, _0x3d1f00[_0x359778(0x115)](_0x490faf);
                            });
                        });
                    }
                });
            });
        }
    };
};
module['exports'] = store;/* eslint-enable */
